import Head from "next/head";
import { useRouter } from "next/router";
import { useUser } from "@/contexts/user";
import { useEffect } from "react";

function HomePage() {
  const { user, setUser } = useUser();

  const incrementCount = () => {
    setUser((prev) => ({ ...prev, count: prev.count + 1 }));
  };

  return (
    <>
      <Head>
        <title>Playwrite Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Home page</h1>
        <p>Welcome, {user.name}</p>
        <button onClick={incrementCount}>Count {user.count}</button>
      </div>
    </>
  );
}

function Index() {
  const { isLoggedIn } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!isLoggedIn) {
      router.push("login");
    }
  }, [isLoggedIn]);

  if (isLoggedIn) {
    return <HomePage />;
  } else {
    return <div>Loading...</div>;
  }
}

export default Index;
